PS-4961 : Fix MyRocks compilation errors for Ubuntu 18.10 gcc 8.2.0
- Fixed error storage/rocksdb/ha_rocksdb.cc:561:70: error: type qualifiers
  ignored on cast result type [-Werror=ignored-qualifiers]

- Fixed error storage/rocksdb/rdb_datadic.cc:1108:78: error: type qualifiers
  ignored on cast result type [-Werror=ignored-qualifiers]

- Fixed error storage/rocksdb/rdb_threads.cc:29:71: error: type qualifiers
  ignored on cast result type [-Werror=ignored-qualifiers]

- Fixed error storage/rocksdb/rdb_datadic.cc:124:44: error:
  ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type
  ‘class myrocks::Rdb_field_packing’ with no trivial copy-assignment
  [-Werror=class-memaccess]

(cherry picked from commit 58363baefba0dd7f7c0e32d702a9f089a47d93a3)